version: '3'
services:
  app:
    container_name: go_container
    build: ./
    tty: true
    working_dir: "/go/src/work"
    ports:
      - "8080:8080"
    volumes:
      - .:/go

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_database
      MYSQL_USER: admin 
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    #command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

volumes:
  db-data:
    driver: local

